### ISSUE TITLE
Can't sign in with Facebook

### ISSUE THREAD

**Issue by olivierobert** [shivabhusal/lacerate#17]
Check the Facebook app settings as it needs to be set to "Live" for non-developers to sign in

![_3__error](https://cloud.githubusercontent.com/assets/696529/23881346/94b480d6-088c-11e7-95cb-5fcc8db2ffb4.png)

**Comment by shivabhusal** [comment]
@olivierobert I am really sorry; I am on it.

**Comment by shivabhusal** [comment]
@olivierobert done!
